### ISSUE TITLE
Error: Cannot find module '/xxx/global/node_modules/sidi-cli/build/SIDI/initial/codemagic/stacks.json'

### ISSUE THREAD

**Issue by odemolliens** [arhs-spikeseed-mobile/sidi-cli#4]
I'm trying to setup a new project and it's failing for an obscure reason:

````
----------------------- Configuring dev... -----------------------

✔ Do you want link the CICD to your repository? (to update git pipeline status .eg) · true
_git_ssh_and_clone not found for codemagic, let's continue to the next step..
✔ Do you want run assets overlayer to customize your app icons? [More info](https://github.com/imranMnts/sidi-cli/blob/master/docs/steps.md#setup_app_assets) · false
✔ Do you want launch native Android lint? · true
✔ Do you want launch native Android unit tests? · true
✔ Do you want build an AAB too? · true
✔ Do you export application's sourcemap? · false
_deploy_to_cicd not found for codemagic, let's continue to the next step..
✔ Do you want send a git tag at the end of the build? · true
✔ Do you want send Slack notification at the end of the build? · true
✔ Do you want send Teams notification at the end of the build? · true

----------------------- We are searching: AndroidManifest.xml -----------------------

Sidi found one file
Path: android&#x2F;app&#x2F;src&#x2F;main&#x2F;AndroidManifest.xml
AndroidManifest.xml is configured correctly to update version during the build
Sidi didn't find any customSteps.. Continue to the next task
Sidi didn't find any customSteps.. Continue to the next task
/xxx/.config/yarn/global/node_modules/gluegun/build/index.js:15
    throw up;
    ^

Error: Cannot find module '/xxx/.config/yarn/global/node_modules/sidi-cli/build/SIDI/initial/codemagic/stacks.json'
Require stack:
- /xxx/.config/yarn/global/node_modules/sidi-cli/build/src/editors/requests.js
- /xxx/.config/yarn/global/node_modules/sidi-cli/build/src/main/PrepareSteps.js
- /xxx/.config/yarn/global/node_modules/sidi-cli/build/src/main/Generator.js
- /xxx/.config/yarn/global/node_modules/sidi-cli/build/src/gluegun/commands/edit.js
- /xxx/.config/yarn/global/node_modules/gluegun/build/loaders/module-loader.js
- /xxx/.config/yarn/global/node_modules/gluegun/build/loaders/command-loader.js
- /xxx/.config/yarn/global/node_modules/gluegun/build/runtime/runtime.js
- /xxx/.config/yarn/global/node_modules/gluegun/build/domain/builder.js
- /xxx/.config/yarn/global/node_modules/gluegun/build/index.js
- /xxx/.config/yarn/global/node_modules/sidi-cli/build/src/cli.js
- /xxx/.config/yarn/global/node_modules/sidi-cli/bin/sidi-cli
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.Module._load (node:internal/modules/cjs/loader:833:27)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at requestStack (/xxx/.config/yarn/global/node_modules/sidi-cli/build/src/editors/requests.js:36:20)
    at prepareSteps (/xxx/.config/yarn/global/node_modules/sidi-cli/build/src/main/PrepareSteps.js:44:61)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Generator (/xxx/.config/yarn/global/node_modules/sidi-cli/build/src/main/Generator.js:15:27)
    at async Command.run (/xxx/.config/yarn/global/node_modules/sidi-cli/build/src/gluegun/commands/init.js:61:9) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/xxx/.config/yarn/global/node_modules/sidi-cli/build/src/editors/requests.js',
    '/xxx/.config/yarn/global/node_modules/sidi-cli/build/src/main/PrepareSteps.js',
    '/xxx/.config/yarn/global/node_modules/sidi-cli/build/src/main/Generator.js',
    '/xxx/.config/yarn/global/node_modules/sidi-cli/build/src/gluegun/commands/edit.js',
    '/xxx/.config/yarn/global/node_modules/gluegun/build/loaders/module-loader.js',
    '/xxx/.config/yarn/global/node_modules/gluegun/build/loaders/command-loader.js',
    '/xxx/.config/yarn/global/node_modules/gluegun/build/runtime/runtime.js',
    '/xxx/.config/yarn/global/node_modules/gluegun/build/domain/builder.js',
    '/xxx/.config/yarn/global/node_modules/gluegun/build/index.js',
    '/xxx/.config/yarn/global/node_modules/sidi-cli/build/src/cli.js',
    '/xxx/.config/yarn/global/node_modules/sidi-cli/bin/sidi-cli'
  ]
}

````

**Comment by imranMnts** [comment]
The issue has been fixed in v3.0.2.

Thanks for the report.
